version: "2"

services:
  mongo:
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    security_opt:
      - no-new-privileges
    container_name: mongo-db
    hostname: db
    image: mongo
    #    environment:
    #      - MONGO_INITDB_ROOT_USERNAME=username
    #      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    #    volumes:
    #      - "$PWD/docker/mongo/:/docker-entrypoint-initdb.d/"
    command: mongod
  redis:
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    security_opt:
      - no-new-privileges
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass "redis_test"
  api:
    container_name: otc-api
    build: ./
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    security_opt:
      - no-new-privileges
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: node /api/dist/src/app.js
    volumes:
      - ./.env:/api/.env
      - ./logs:/api/logs/
    env_file: .env
